services:
  mongo:
    image: mongo:6
    container_name: restaurant-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: andresbolivarsam
      MONGO_INITDB_ROOT_PASSWORD: qweQAWledEm4m9zB
    volumes:
      - mongo_data:/data/db   # volumen persistente

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant-backend
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    depends_on:
      - mongo
    volumes:
      # Montar el código fuente para hot reload (excluyendo node_modules)
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    # Mantener el contenedor corriendo
    stdin_open: true
    tty: true

volumes:
  mongo_data:
